# Generated by Django 3.2.3 on 2021-05-31 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cui', models.TextField()),
                ('nombres', models.TextField()),
                ('apellidos', models.TextField()),
                ('escuela', models.TextField()),
            ],
        ),
    ]
